[Telegram]
token = 8868540047:AAFiUfedDuiUqLBbjoyYBlMh3stXiFfSweI
chat_id = -1003525770211
#chat_id = -5105606582

[AllowedUsers]
user_ids = 5063990366

[Schedule]
mode = daily
time = 9:00, 21:00
interval_minutes = 120

# ====== ОБЩИЕ НАСТРОЙКИ ГРАФИКОВ ======
[Plot_1]
columns = toe, impact_angle_x
title = Toe, Impact Angle X
ylabel = Градус
kind = line

[Plot_2]
columns = fill
title = Объем
ylabel = Объем %%
kind = line

[Plot_3]
columns = ts
title = Время оборота
ylabel = Время, мс
kind = line

[Plot_4]
columns = Vmin, Vmax
title = Напряжение
ylabel = mV
kind = line

# ====== Озерный =======
[Factory_Ozerniy]
milluuid = 31aad687-8ce1-4aae-9f1d-bacd2648bee4
host = 192.168.4.16
port = 8080
from_minutes = -720
to_minutes = 0
figsize = 14,8
rows = 2
cols = 2
grid = True
save = subplot1.png
msg = Озерный
plots = Plot_1, Plot_2, Plot_3, Plot_4

# ====== Култума =======
[Factory_Kultuma]
milluuid = 4b450068-12f2-44e2-8c84-55124e9d43bd
host = 192.168.4.21
port = 8080
from_minutes = -720
to_minutes = 0
figsize = 14,8
rows = 2
cols = 2
grid = True
save = subplot4.png
msg = Култума
plots = Plot_1, Plot_2, Plot_3, Plot_4

# ====== Полиметалл Албазино =======
[Factory_Albasino]
milluuid = 8e5df0c6-a7f3-4a17-afde-7395c6e39625
host = 192.168.4.18
port = 8080
from_minutes = -720
to_minutes = 0
figsize = 14,8
rows = 2
cols = 2
grid = True
save = subplot2.png
msg = Полиметалл Албазино
plots = Plot_1, Plot_2, Plot_3, Plot_4

# ====== Русал =======
[Factory_Rusal]
milluuid = 366fc18b-64a2-4969-a3d9-ad99373dc888
host = 192.168.4.8
port = 8080
from_minutes = -720
to_minutes = 0
figsize = 14,8
rows = 2
cols = 2
grid = True
save = subplot3.png
msg = Русал
plots = Plot_1, Plot_2, Plot_3, Plot_4
