[Telegram]
token = 8868540047:AAFiUfedDuiUqLBbjoyYBlMh3stXiFfSweI
chat_id = -1003525770211

[AllowedUsers]
user_ids = 5063990366

[Schedule]
mode = daily
time = 19:54
interval_minutes = 120

# ====== ОБЩИЕ НАСТРОЙКИ ГРАФИКОВ ======
[Plot_1]
columns = toe, impact_angle_x
title = Toe, Impact Angle X
ylabel = Градус
kind = line

[Plot_2]
columns = fill
title = Объем
ylabel = Объем %%
kind = line

[Plot_3]
columns = ts
title = Время оборота
ylabel = Время, мс
kind = line

[Plot_4]
columns = ts, fill, toe, impact_angle_x
title = Совмещённый график
ylabel = Время, мс
kind = line
colors = blue, red, green, orange
left_columns = ts
left_ylabel = Время, мс
right1_columns = toe, impact_angle_x
right1_ylabel = Toe, градусы
right2_columns = fill
right2_ylabel = Объем

# ====== Озерный =======
[Subplot_1]
milluuid = 31aad687-8ce1-4aae-9f1d-bacd2648bee4
host = 192.168.4.16
port = 8080
from_minutes = -720
to_minutes = 0
figsize = 14,8
rows = 2
cols = 2
grid = True
save = subplot1.png
msg = Озерный
plots = Plot_1, Plot_2, Plot_3, Plot_4

# ====== Полиметалл Албазино =======
[Subplot_2]
milluuid = 8e5df0c6-a7f3-4a17-afde-7395c6e39625
host = 192.168.4.18
port = 8080
from_minutes = -720
to_minutes = 0
figsize = 14,8
rows = 2
cols = 2
grid = True
save = subplot2.png
msg = Полиметалл Албазино
plots = Plot_1, Plot_2, Plot_3, Plot_4